"""add hub_providers

Revision ID: 08997b81d33c
Revises: g7a8b9c0d1e2
Create Date: 2026-05-01 11:35:04.762996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08997b81d33c'
down_revision: Union[str, None] = 'g7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_providers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Insert default providers
    op.execute("INSERT INTO hub_providers (id, name, provider_type) VALUES ('google', 'Google AI (Gemini)', 'google_genai')")
    op.execute("INSERT INTO hub_providers (id, name, provider_type) VALUES ('openrouter', 'OpenRouter', 'openai_compatible')")
    op.execute("INSERT INTO hub_providers (id, name, provider_type) VALUES ('ollama', 'Ollama (Local)', 'openai_compatible')")
    
    op.create_foreign_key(None, 'hub_llm_configs', 'hub_providers', ['provider'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hub_llm_configs', type_='foreignkey')
    op.drop_table('hub_providers')
    # ### end Alembic commands ###
