"""initial_schema

Revision ID: 8879cf0a3197
Revises: 
Create Date: 2026-04-22 20:45:49.489446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8879cf0a3197'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminaccount',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_adminaccount_email'), 'adminaccount', ['email'], unique=True)
    op.create_table('aiconfig',
    sa.Column('role_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role_key')
    )
    op.create_table('automation_library',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('PDF_EXTRACTOR', 'RPA_WEB', 'ETL_TRANSFORM', 'CHART_GENERATOR', 'CUSTOM_SCRIPT', 'WORKFLOW', name='automationtype'), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('partner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_workflow', sa.Boolean(), nullable=False),
    sa.Column('access_groups', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_library_client_id'), 'automation_library', ['client_id'], unique=False)
    op.create_index(op.f('ix_automation_library_id'), 'automation_library', ['id'], unique=False)
    op.create_index(op.f('ix_automation_library_name'), 'automation_library', ['name'], unique=False)
    op.create_index(op.f('ix_automation_library_partner_id'), 'automation_library', ['partner_id'], unique=False)
    op.create_table('extractionserviceconfig',
    sa.Column('service_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_prompt_template', sa.Text(), nullable=True),
    sa.Column('expected_schema', sa.JSON(), nullable=True),
    sa.Column('suggested_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier_override', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('modelcache',
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('models', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('modelpricing',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_cost_per_m', sa.Float(), nullable=False),
    sa.Column('output_cost_per_m', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partneraccount',
    sa.Column('partner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_table('schedulerconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('refresh_hour', sa.Integer(), nullable=False),
    sa.Column('refresh_minute', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systemprompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('context_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemprompt_name'), 'systemprompt', ['name'], unique=True)
    op.create_table('tokenlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('script_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trustedscript',
    sa.Column('script_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('script_id')
    )
    op.create_table('clientaccount',
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('partner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nif', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partneraccount.partner_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('billingrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('partner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientaccount.client_id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partneraccount.partner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clienttelemetrylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manifest_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimated', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp_client', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientaccount.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clienttelemetrylog_client_id'), 'clienttelemetrylog', ['client_id'], unique=False)
    op.create_index(op.f('ix_clienttelemetrylog_machine_id'), 'clienttelemetrylog', ['machine_id'], unique=False)
    op.create_index(op.f('ix_clienttelemetrylog_manifest_id'), 'clienttelemetrylog', ['manifest_id'], unique=False)
    op.create_table('license',
    sa.Column('license_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quota_tokens', sa.Integer(), nullable=False),
    sa.Column('consumed_tokens', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientaccount.client_id'], ),
    sa.PrimaryKeyConstraint('license_id')
    )
    op.create_table('scriptescalation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_code', sa.Text(), nullable=True),
    sa.Column('escalation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientaccount.client_id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partneraccount.partner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scriptescalation_client_id'), 'scriptescalation', ['client_id'], unique=False)
    op.create_index(op.f('ix_scriptescalation_partner_id'), 'scriptescalation', ['partner_id'], unique=False)
    op.create_table('server_security_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('partner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_domains', sa.Text(), nullable=True),
    sa.Column('allowed_libraries', sa.Text(), nullable=True),
    sa.Column('forbidden_libraries', sa.Text(), nullable=True),
    sa.Column('screenshot_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trusted_screenshot_domains', sa.Text(), nullable=True),
    sa.Column('max_execution_time', sa.Integer(), nullable=False),
    sa.Column('max_memory_mb', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clientaccount.client_id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partneraccount.partner_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_security_policy_client_id'), 'server_security_policy', ['client_id'], unique=False)
    op.create_index(op.f('ix_server_security_policy_partner_id'), 'server_security_policy', ['partner_id'], unique=False)
    op.create_table('licenseactivation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('machine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['license.license_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenseactivation_license_id'), 'licenseactivation', ['license_id'], unique=False)
    op.create_index(op.f('ix_licenseactivation_machine_id'), 'licenseactivation', ['machine_id'], unique=False)
    op.create_table('licenseauditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('performed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['license.license_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenseauditlog_license_id'), 'licenseauditlog', ['license_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licenseauditlog_license_id'), table_name='licenseauditlog')
    op.drop_table('licenseauditlog')
    op.drop_index(op.f('ix_licenseactivation_machine_id'), table_name='licenseactivation')
    op.drop_index(op.f('ix_licenseactivation_license_id'), table_name='licenseactivation')
    op.drop_table('licenseactivation')
    op.drop_index(op.f('ix_server_security_policy_partner_id'), table_name='server_security_policy')
    op.drop_index(op.f('ix_server_security_policy_client_id'), table_name='server_security_policy')
    op.drop_table('server_security_policy')
    op.drop_index(op.f('ix_scriptescalation_partner_id'), table_name='scriptescalation')
    op.drop_index(op.f('ix_scriptescalation_client_id'), table_name='scriptescalation')
    op.drop_table('scriptescalation')
    op.drop_table('license')
    op.drop_index(op.f('ix_clienttelemetrylog_manifest_id'), table_name='clienttelemetrylog')
    op.drop_index(op.f('ix_clienttelemetrylog_machine_id'), table_name='clienttelemetrylog')
    op.drop_index(op.f('ix_clienttelemetrylog_client_id'), table_name='clienttelemetrylog')
    op.drop_table('clienttelemetrylog')
    op.drop_table('billingrecord')
    op.drop_table('clientaccount')
    op.drop_table('trustedscript')
    op.drop_table('tokenlog')
    op.drop_index(op.f('ix_systemprompt_name'), table_name='systemprompt')
    op.drop_table('systemprompt')
    op.drop_table('schedulerconfig')
    op.drop_table('partneraccount')
    op.drop_table('modelpricing')
    op.drop_table('modelcache')
    op.drop_table('extractionserviceconfig')
    op.drop_index(op.f('ix_automation_library_partner_id'), table_name='automation_library')
    op.drop_index(op.f('ix_automation_library_name'), table_name='automation_library')
    op.drop_index(op.f('ix_automation_library_id'), table_name='automation_library')
    op.drop_index(op.f('ix_automation_library_client_id'), table_name='automation_library')
    op.drop_table('automation_library')
    op.drop_table('aiconfig')
    op.drop_index(op.f('ix_adminaccount_email'), table_name='adminaccount')
    op.drop_table('adminaccount')
    # ### end Alembic commands ###
