"""issue102 last_login_at en superadminaccount y adminaccount

Revision ID: 96acb5e218ec
Revises: e5fa9688d218
Create Date: 2026-09-22 22:53:18.347324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96acb5e218ec'
down_revision: Union[str, None] = 'e5fa9688d218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminaccount', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('superadminaccount', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('superadminaccount', 'last_login_at')
    op.drop_column('adminaccount', 'last_login_at')
    # ### end Alembic commands ###
