from typing import List, Optional
import uuid
from automatia_shared.dtos import FlowSpec, TaskSpec
from automatia_shared.enums import StepType

class BridgeService:
    """
    Servicio encargado de inyectar 'pasos puente' (bridge tasks) en un workflow
    para resolver incompatibilidades de datos entre pasos contiguos.
    """
    def __init__(self, flow: FlowSpec):
        """
        Inicializa el servicio con una especificación de flujo existente.
        """
        self.flow = flow

    def inject_bridge_task(self, at_index: int, code: str, inputs: List[str], outputs: List[str]) -> FlowSpec:
        """
        Inserta un nuevo paso de tipo CUSTOM_SCRIPT en una posición específica del flujo.
        Este paso actúa como transformador de datos.

        Args:
            at_index: Índice de la lista de pasos donde insertar el puente.
            code: Código fuente Python del script de transformación.
            inputs: Lista de variables que el puente consumirá.
            outputs: Lista de variables que el puente producirá.

        Returns:
            El objeto FlowSpec actualizado con el nuevo paso inyectado.
        """
        
        bridge_task = TaskSpec(
            # id=f"bridge_{at_index}_{uuid.uuid4().hex[:4]}", # ID generated automatically/managed by DB usually, here manually for DTO
            name="Puente de Transformación",
            type=StepType.CUSTOM_SCRIPT,
            script_code=code,
            inputs=inputs,
            outputs=outputs,
            metadata={'is_bridge': True, 'auto_generated': True}
        )
        
        # Insertamos en la posición indicada
        self.flow.steps.insert(at_index, bridge_task)
        
        return self.flow

    async def generate_bridge_code(self, 
                                   source_var: str, 
                                   source_type: str, 
                                   target_var: str, 
                                   target_type: str,
                                   context: Optional[dict] = None) -> str:
        """
        Genera el código REAL del puente utilizando IA.
        
        Args:
            source_var: Nombre de la variable fuente.
            source_type: Tipo de datos fuente (ej. "List[Dict]").
            target_var: Nombre de la variable destino.
            target_type: Tipo de datos destino (ej. "DataFrame").
            context: Contexto adicional (ejemplos, schema).
            
        Returns:
            Código Python generado.
        """
        try:
            from client_app.app.services.bridge_generation_service import bridge_generation_service
            
            # Generar la función de transformación
            transform_func_code = await bridge_generation_service.generate_bridge_code(
                source_type=source_type,
                target_type=target_type,
                context=context
            )
            
            # Envolver en la estructura esperada por el Custom Script runner
            # El runner espera que el script defina una función main() o similar, 
            # pero aquí asumimos que el Custom Script expone variables.
            # Lo estándar es que el script ejecute y asigne a variables de salida.
            
            wrapper_code = f"""
# Smart Bridge: {source_var} ({source_type}) -> {target_var} ({target_type})
# Auto-generated by Brain AI

{transform_func_code}

# Execution
try:
    if '{source_var}' in globals():
        input_data = globals()['{source_var}']
        result = transform(input_data)
        # Assign to target variable
        {target_var} = result
    else:
        raise ValueError("Source variable '{source_var}' not found in context")
except Exception as e:
    raise RuntimeError(f"Bridge transformation failed: {{e}}")
"""
            return wrapper_code
            
        except Exception as e:
            print(f"Error generating smart bridge: {e}")
            return self.generate_bridge_code_mock(target_var, source_var)

    def generate_bridge_code_mock(self, missing_var: str, source_var: str) -> str:
        """
        Fallback/Mock para generación de código de puente.
        """
        return f"""
# Fallback Bridge
def transform(data):
    return data

if '{source_var}' in globals():
    {missing_var} = transform(globals()['{source_var}'])
else:
    {missing_var} = None
"""
